version: '2'
services:
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"
  movie:
    build: .
    ports:
      - "8080:8080"
    volumes:
     - .:/code
    links:
     - mongo
    depends_on:
      - "mongo"